### ISSUE TITLE
CPU(wu) only shows "In" instead of Intel Core i3-7020U

### ISSUE THREAD

**Issue by mdartmann** [TheDarkBug/uwufetch#56]
CPU only shows `In` instead of the proper model name on i3-7020u.

OS: Arch Linux, Build: AUR `uwufetch`

`lshw` output for CPU:

```
*-cpu
          description: CPU
          product: Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
          vendor: Intel Corp.
          physical id: 4
          bus info: cpu@0
          version: Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
          serial: To Be Filled By O.E.M.
          slot: U3E1
          size: 714MHz
          capacity: 4005MHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d cpufreq
          configuration: cores=2 enabledcores=2 threads=4
        *-cache:0
             description: L1 cache
             physical id: 5
             slot: L1 Cache
             size: 128KiB
             capacity: 128KiB
             capabilities: synchronous internal write-back unified
             configuration: level=1
        *-cache:1
             description: L2 cache
             physical id: 6
             slot: L2 Cache
             size: 512KiB
             capacity: 512KiB
             capabilities: synchronous internal write-back unified
             configuration: level=2
        *-cache:2
             description: L3 cache
             physical id: 7
             slot: L3 Cache
             size: 3MiB
             capacity: 3MiB
             capabilities: synchronous internal write-back unified
             configuration: level=3
```

`uwufetch` screenshot:  

![Screenshot_20210330_184703](https://user-images.githubusercontent.com/76077644/113025794-a2552180-9188-11eb-9b54-33f2adfc18b7.png)

**Comment by TheDarkBug** [comment]
I think that you didn't update the package, i solved this in #39. Updating the package should solve the issue.

**Comment by mdartmann** [comment]
Either the AUR package is not up to date or it isn't fixed.
![Screenshot_20210330_210359](https://user-images.githubusercontent.com/76077644/113042474-87d87380-919b-11eb-8000-a5349b6d09f3.png)

**Comment by TheDarkBug** [comment]
> The issue is fixed in `uwufetch-git`, not the `uwufetch` binary.
I'll publish a release for bug fixes as soon as I can

**Comment by TheDarkBug** [comment]
I just released 42e7123 and updated the [aur package](https://aur.archlinux.org/packages/uwufetch/).
